In [67]:
import numpy as np
import scipy.linalg
import matplotlib.pyplot as plt

In [11]:
A1 = np.array([
    [1, 1, 0],
    [1, 0, 1],
])
A1tA1 = np.array([
    [2, 1, 1],
    [1, 1, 0],
    [1, 0, 1]
])

In [12]:
np.poly(A1tA1)

array([ 1.00000000e+00, -4.00000000e+00,  3.00000000e+00,  8.74300632e-16])

In [13]:
v11 = np.array([0, 1, -1]).T
v12 = np.array([2, 1, 1]).T

In [14]:
A1@v11

array([ 1, -1])

In [15]:
A1@v12

array([3, 3])

In [18]:
np.linalg.pinv(A1)

array([[ 0.33333333,  0.33333333],
       [ 0.66666667, -0.33333333],
       [-0.33333333,  0.66666667]])

In [19]:
np.linalg.pinv(A1)@(np.array([2,3]).T)

array([1.66666667, 0.33333333, 1.33333333])

In [20]:
### Q2

In [27]:
A2 = np.array([[-1, 0, 1], [-1, -2, 3], [-1, -4, 5]])
A2

array([[-1,  0,  1],
       [-1, -2,  3],
       [-1, -4,  5]])

In [26]:
(A2.T)@A2

array([[  3,   6,  -9],
       [  6,  20, -26],
       [ -9, -26,  35]])

In [53]:
A2@A2

array([[  0,  -4,   4],
       [  0,  -8,   8],
       [  0, -12,  12]])

In [54]:
A2-2*np.eye(3)

array([[-3.,  0.,  1.],
       [-1., -4.,  3.],
       [-1., -4.,  3.]])

In [59]:
scipy.linalg.null_space(A2-2*np.eye(3))

array([[0.26726124],
       [0.53452248],
       [0.80178373]])

In [63]:
P = np.asarray([[1, 2, 3], [1, 1, 1], [0, 1, 1]]).T
J = np.asarray([[2, 0, 0], [0, 0, 1], [0, 0, 0]])
J1 = np.asarray([[1/2, 0, 0], [0, 0, 0], [0, 0, 0]])
P1 = np.linalg.inv(P)
print(P1)
P@J@P1

[[ 0. -1.  1.]
 [ 1.  1. -1.]
 [-1.  2. -1.]]


array([[-1.,  0.,  1.],
       [-1., -2.,  3.],
       [-1., -4.,  5.]])

In [66]:
P@J1@P1

array([[ 0. , -0.5,  0.5],
       [ 0. , -1. ,  1. ],
       [ 0. , -1.5,  1.5]])

In [29]:
np.poly(A2)

array([ 1.00000000e+00, -2.00000000e+00,  3.70074342e-17, -1.11022302e-16])

In [35]:
np.linalg.matrix_rank(A2)

2

In [30]:
np.linalg.eig(A2)

(array([-4.62592927e-18+7.4505806e-09j, -4.62592927e-18-7.4505806e-09j,
         2.00000000e+00+0.0000000e+00j]),
 array([[-0.57735027+0.00000000e+00j, -0.57735027-0.00000000e+00j,
          0.26726124+0.00000000e+00j],
        [-0.57735027-4.30159471e-09j, -0.57735027+4.30159471e-09j,
          0.53452248+0.00000000e+00j],
        [-0.57735027-4.30159471e-09j, -0.57735027+4.30159471e-09j,
          0.80178373+0.00000000e+00j]]))

In [22]:
np.linalg.pinv(A2)

array([[-0.63888889, -0.22222222,  0.19444444],
       [ 0.44444444,  0.11111111, -0.22222222],
       [ 0.19444444,  0.11111111,  0.02777778]])

In [37]:
# Q 1-2
A3 = np.array([
    [2, 2],
    [-1, 2],
    [1, 1],
    [-2, 3]
])
A3

array([[ 2,  2],
       [-1,  2],
       [ 1,  1],
       [-2,  3]])

In [41]:
b3 = np.array([1, 2, 3, 4]).T
b3

array([1, 2, 3, 4])

In [43]:
B3 = A3.T@A3
B3

array([[10, -3],
       [-3, 18]])

In [44]:
np.linalg.pinv(A3)

array([[ 0.24561404, -0.07017544,  0.12280702, -0.15789474],
       [ 0.15204678,  0.0994152 ,  0.07602339,  0.14035088]])

In [46]:
np.linalg.pinv(A3)@(np.asarray([1,2,3,4]).T)

array([-0.15789474,  1.14035088])

In [51]:
pA3 = np.array([[41, -12, 21, -27], [26, 17, 13, 24]])
pA3

array([[ 41, -12,  21, -27],
       [ 26,  17,  13,  24]])

In [52]:
pA3@(np.asarray([1,2,3,4]).T)

array([-28, 195])