In [2]:
import numpy as np

In [111]:
def calc_stationary(P):
    # P is required to be positive, and column sum should be 1
    import scipy.linalg
    pinv = scipy.linalg.null_space(P-np.eye(P.shape[0]))
    return pinv/np.sum(pinv, axis=0)

In [3]:
A = np.array([[4,1],[-1,2]])

In [4]:
np.poly(A)

array([ 1., -6.,  9.])

In [5]:
np.roots(np.poly(A))

array([3.+3.7252903e-08j, 3.-3.7252903e-08j])

In [8]:
np.array([[1,1],[-1,0]])@np.array([[100,100],[0,100]])@np.array([[0,-1],[1,1]])

array([[ 200,  100],
       [-100,    0]])

In [26]:
# for exp(At) from exp(Jt)
np.array([[1,1],[-1,0]])@np.array([[100,1000],[0,100]])@np.array([[0,-1],[1,1]])

array([[ 1100,  1000],
       [-1000,  -900]])

In [9]:
A2 = np.array([[1,-1],[1,1]])

In [12]:
np.poly(A2)

array([ 1., -2.,  2.])

In [11]:
np.roots(np.poly(A2))

array([1.+1.j, 1.-1.j])

In [16]:
np.linalg.inv(np.array([[complex(0,1),-1],[complex(0,1),1]]))

array([[ 0. -0.5j,  0. -0.5j],
       [-0.5+0.j ,  0.5+0.j ]])

In [17]:
np.linalg.inv(np.array([[-complex(0,1),1],[complex(0,1),1]]))

array([[-0. +0.5j,  0. -0.5j],
       [ 0.5+0.j ,  0.5+0.j ]])

In [18]:
complex(0,1)

1j

In [22]:
np.linalg.inv(np.array([[complex(0,1),complex(0,1)],[-1,1]]))

array([[ 0. -0.5j, -0.5-0.j ],
       [ 0. -0.5j,  0.5+0.j ]])

In [23]:
np.exp(complex(1,-1))

(1.4686939399158851-2.2873552871788423j)

In [25]:
np.array([[complex(0,1),complex(0,1)],[-1,1]])@np.array([[200,0],[0,2000]])@np.linalg.inv(np.array([[complex(0,1),complex(0,1)],[-1,1]]))

array([[1100.  +0.j,    0.+900.j],
       [   0.-900.j, 1100.  +0.j]])

In [72]:
P = np.array([ [1/6, 2/5, 1/3],
[0, 2/5, 1/3],
[5/6, 1/5, 1/3]])
## v0 = np.array([1/4,
## 1/3,
## 1/2]).T, not P vector, changed to 1/4,1/4,1/2
v1 = np.array([1,
0,
0]).T
P

array([[0.16666667, 0.4       , 0.33333333],
       [0.        , 0.4       , 0.33333333],
       [0.83333333, 0.2       , 0.33333333]])

In [108]:
# P is not positive
P@P

array([[0.30555556, 0.29333333, 0.3       ],
       [0.27777778, 0.22666667, 0.24444444],
       [0.41666667, 0.48      , 0.45555556]])

In [109]:
calc_stationary(P@P)

array([[0.3 ],
       [0.25],
       [0.45]])

In [118]:
calc_stationary(P)

array([[0.3 ],
       [0.25],
       [0.45]])

In [73]:
v0

array([0.25      , 0.33333333, 0.5       ])

In [74]:
P@P@P@P@P@v0

array([0.32499919, 0.27082928, 0.48750487])

In [75]:
def powerP(P, v0, k):
    P2 = P
    Pk = np.eye(P.shape[0])
    while(k):
        if(k%2 == 1):
            Pk = P2@Pk
        P2 = P2@P2
        #print(P2)
        #print(Pk)
        #print(k)
        k = k//2
    return Pk@v0

In [76]:
powerP(P, v0, 10000)

array([0.325     , 0.27083333, 0.4875    ])

In [78]:
powerP(P, v1, 10000)

array([0.3 , 0.25, 0.45])

In [92]:
import scipy.linalg
p1inv = scipy.linalg.null_space(P-np.eye(P.shape[0]))
p1inv/np.sum(p1inv)

array([[0.3 ],
       [0.25],
       [0.45]])

In [113]:
P2 = np.array([ [0.6, 0.3, 0.3],
[0.2, 0.3, 0.2],
[0.2, 0.4, 0.5]])

In [114]:
calc_stationary(P2)

array([[0.42857143],
       [0.22222222],
       [0.34920635]])

In [117]:
v21 = np.array([[27 ],
       [14],
       [22]])
print(np.sum(v21, axis=0))
v21/np.sum(v21, axis=0)

[63]


array([[0.42857143],
       [0.22222222],
       [0.34920635]])

In [81]:
powerP(P2, v1, 10000)

array([0.42857143, 0.22222222, 0.34920635])

In [90]:
import scipy.linalg
pinv = scipy.linalg.null_space(P2-np.eye(P2.shape[0]))
pinv/np.sum(pinv)

array([[0.42857143],
       [0.22222222],
       [0.34920635]])

In [95]:
P3 = np.array([ [1, 0, 0],
[0, 0, 1],
[0, 1, 0]])
v31 = np.array([1, 0, 0]).T
v32 = np.array([0, 0, 1]).T
v33 = np.array([0.5, 0.5, 0]).T

In [96]:
powerP(P3, v31, 10000)

array([1., 0., 0.])

In [97]:
powerP(P3, v32, 10000)

array([0., 0., 1.])

In [98]:
powerP(P3, v33, 10000)

array([0.5, 0.5, 0. ])

In [105]:
calc_stationary(P3)

array([[0. , 1. ],
       [0.5, 0. ],
       [0.5, 0. ]])

In [106]:
P4 = np.array([ [0.1, 0.1, 0.1],
[0.1, 0.1, 0.1],
[0.8, 0.8, 0.8]])

In [107]:
calc_stationary(P4)

array([[0.1],
       [0.1],
       [0.8]])

In [120]:
AA = np.array([
    [1/5, 2/3, 1/4],
    [3/5, 0, 1/2],
    [1/5, 1/3, 1/4]
])

In [122]:
AA@AA

array([[0.49      , 0.21666667, 0.44583333],
       [0.22      , 0.56666667, 0.275     ],
       [0.29      , 0.21666667, 0.27916667]])

In [121]:
calc_stationary(AA)

array([[0.38043478],
       [0.35869565],
       [0.26086957]])