In [8]:
import numpy as np
from scipy.linalg import null_space

In [9]:
A1 = np.asarray(
[
    [0, 1, 0, 1],
    [0, 0, 1, 0],
    [-1, -2, 2, -3],
    [0, -1, 0, -1],
])

In [10]:
##np.poly()

In [11]:
np.poly(A1)

array([ 1.00000000e+00, -1.00000000e+00, -7.76414116e-16, -1.31412821e-15,
       -4.94282065e-16])

In [12]:
A2 = np.asarray(
    [
        [4,1,2,5],
        [-1,-2,-1,-3],
        [1, 3, 3, 4],
        [-1,0, -1,-1]
    ])

In [13]:
np.poly(A2)

array([ 1.00000000e+00, -4.00000000e+00,  4.00000000e+00,  1.40831370e-15,
       -5.54320636e-15])

A2@A2

In [13]:
A13 = A1@A1@A1
A13

array([[-1, -1,  1, -2],
       [-2, -2,  2, -4],
       [-2, -2,  2, -4],
       [ 1,  1, -1,  2]])

In [14]:
A2@A2

array([[12,  8,  8, 20],
       [ 0,  0,  0,  0],
       [ 0,  4,  4,  4],
       [-4, -4, -4, -8]])

In [22]:
A3 = np.asarray(
[[2, -1, 0 ,1],
[0, -2, -1, -2],
[0, -1, -1, -1],
[-1, 2, 1, 1]])

In [23]:
np.poly(A3)

array([ 1.00000000e+00, -1.40713179e-15, -1.45165400e-16, -2.83602547e-15,
       -1.18491845e-15])

In [24]:
A3@A3@A3@A3

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
null_space(A13.T)

array([[-0.9486833 , -0.        ,  0.        ],
       [ 0.21081851, -0.74535599,  0.        ],
       [ 0.21081851,  0.59628479,  0.4472136 ],
       [-0.10540926, -0.2981424 ,  0.89442719]])

In [ ]:
x+y-z+2w=0, [1, -1, 0, 0], [1, 0, 1, 0], [2, 0, 0, -1]