In [11]:
import numpy as np
from scipy.linalg import null_space
import scipy.linalg

In [40]:
A1 = np.asarray(
[
    [0, 9, 0, 0],
    [2, 0, 5, -1],
    [0, -4, 0, 0],
    [0, -2, 0, 0],
])

A2 = np.asarray(
[
    [2, 5, 1, 0],
    [-1, -2, 0, -1],
    [1, 0, -2, 5],
    [0, -1, -1, 2],
])

A3 = np.asarray(
[
    [8, 12, -1, 5],
    [-4, -6, 1, -2],
    [4, 4, 1, 7],
    [-3, -4, 0, -3],
])

In [52]:
def print_ranks(A1):
    print(A1)
    print(np.linalg.matrix_rank(A1))
    print(A1@A1)
    print(np.linalg.matrix_rank(A1@A1))
    print(A1@A1@A1)
    print(np.linalg.matrix_rank(A1@A1@A1))
    #print(np.linalg.matrix_rank(A1@A1@A1@A1))
    #print(np.linalg.matrix_rank(A1@A1@A1@A1@A1))
    print(np.poly(A1))  #1, 2, 3 all x4

In [53]:
print_ranks(A1)

[[ 0  9  0  0]
 [ 2  0  5 -1]
 [ 0 -4  0  0]
 [ 0 -2  0  0]]
2
[[ 18   0  45  -9]
 [  0   0   0   0]
 [ -8   0 -20   4]
 [ -4   0 -10   2]]
1
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
0
[ 1.00000000e+00  2.66121208e-18  8.65927928e-16 -1.17747671e-22
  0.00000000e+00]


In [54]:
print_ranks(A2)

[[ 2  5  1  0]
 [-1 -2  0 -1]
 [ 1  0 -2  5]
 [ 0 -1 -1  2]]
2
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
0
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
0
[ 1.00000000e+00 -9.10639196e-16 -3.69808364e-16 -7.86089943e-32
  1.63131423e-32]


In [55]:
print_ranks(A3)

[[ 8 12 -1  5]
 [-4 -6  1 -2]
 [ 4  4  1  7]
 [-3 -4  0 -3]]
3
[[-3  0  3 -6]
 [ 2  0 -1  5]
 [-1  0  1 -2]
 [ 1  0 -1  2]]
2
[[  6   0   6  24]
 [ -3   0  -3 -12]
 [  2   0   2   8]
 [ -2   0  -2  -8]]
1
[ 1.00000000e+00  7.77560827e-17 -2.91329986e-14  8.19104982e-15
 -1.60355822e-14]


In [56]:
A = np.asarray(
[
    [-10, -7, -2, 0, -4, 2],
    [13, 6, -2, -3, 4, -1],
    [6, 1, -2, 0, 0, 2]
])

In [57]:
np.linalg.matrix_rank(A)

3

In [58]:
A = np.asarray(
[
    [-10, -7, -2, 0, -4, 2],
    [13, 6, -2, -3, 4, -1],
    [6, 1, -2, 0, 0, 2],
    [0, 1, 2, 2, 0, 0]
])
np.linalg.matrix_rank(A)

3