In [35]:
import numpy as np
from scipy.linalg import null_space
import scipy.linalg

A1 = np.asarray(
[
    [0, 0, 2, -1],
    [-2, 3, 2, -1],
    [-3, 0, 5, -1],
    [0, 0, 0, 3],
])

A2 = np.asarray(
[
    [1, 0, 0, 0],
    [0, 0, 1, 0],
    [0, -1, -1, 1],
    [0, 1, 0, -2],
])

A3 = np.asarray(
[
    [-1, 1, 0, 0],
    [0, 0, 0, 1],
    [1, -1, 0, 2],
    [3, -2, -1, 3],
])

In [3]:
A13 = A1-3*np.eye(4)

In [4]:
A13

array([[-3.,  0.,  2., -1.],
       [-2.,  0.,  2., -1.],
       [-3.,  0.,  2., -1.],
       [ 0.,  0.,  0.,  0.]])

In [5]:
A13@A13

array([[ 3.,  0., -2.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 3.,  0., -2.,  1.],
       [ 0.,  0.,  0.,  0.]])

In [6]:
A13@np.asarray([2, 0, 3, 0])

array([0., 2., 0., 0.])

In [8]:
A13@np.asarray([-1, 0, 0, 3])

array([ 0., -1.,  0.,  0.])

In [23]:
A21 = A2+1*np.eye(4)
A21

array([[ 2.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  0.],
       [ 0., -1.,  0.,  1.],
       [ 0.,  1.,  0., -1.]])

In [24]:
np.linalg.matrix_rank(A21)

3

In [25]:
np.linalg.matrix_rank(A21@A21)

2

In [26]:
np.linalg.matrix_rank(A21@A21@A21)

1

In [28]:
A2m1 = A2-1*np.eye(4)
A2m1

array([[ 0.,  0.,  0.,  0.],
       [ 0., -1.,  1.,  0.],
       [ 0., -1., -2.,  1.],
       [ 0.,  1.,  0., -3.]])

In [29]:
np.linalg.matrix_rank(A2m1)

3

In [31]:
A21@np.asarray([0, 0, 1, 0])

array([0., 1., 0., 0.])

In [33]:
A21@np.asarray([0, 1, 0, 0])

array([ 0.,  1., -1.,  1.])

In [34]:
A21@np.asarray([0, 1, -1, 1])

array([0., 0., 0., 0.])

In [40]:
print(A3)
print(np.linalg.matrix_rank(A3))

[[-1  1  0  0]
 [ 0  0  0  1]
 [ 1 -1  0  2]
 [ 3 -2 -1  3]]
3


In [46]:
print(A3@A3)
print(np.linalg.matrix_rank(A3@A3))

[[ 1 -1  0  1]
 [ 3 -2 -1  3]
 [ 5 -3 -2  5]
 [ 5 -2 -3  5]]
2


In [42]:
A31 = A3 - 1*np.eye(4)
print(A31)
print(np.linalg.matrix_rank(A31))

[[-2.  1.  0.  0.]
 [ 0. -1.  0.  1.]
 [ 1. -1. -1.  2.]
 [ 3. -2. -1.  2.]]
3


In [43]:
A31 = A3 - 1*np.eye(4)
print(A31@A31)
print(np.linalg.matrix_rank(A31@A31))

[[ 4. -3.  0.  1.]
 [ 3. -1. -1.  1.]
 [ 3. -1. -1.  1.]
 [-1.  2. -1.  0.]]
2


In [47]:
A3@np.asarray([1,1,1,0])

array([0, 0, 0, 0])

In [50]:
A3@np.asarray([0,1,1,1])

array([1, 1, 1, 0])

In [52]:
A31@np.asarray([1,2,3,2])

array([0., 0., 0., 0.])

In [55]:
A31@np.asarray([0,1,2,3])

array([1., 2., 3., 2.])

In [57]:
A4 = np.asarray([[3,-1],[1,1]])
np.poly(A4)

array([ 1., -4.,  4.])

In [60]:
A42 = A4 - 2*np.eye(2)
A42

array([[ 1., -1.],
       [ 1., -1.]])

In [63]:
np.linalg.matrix_rank(A42)

1

In [64]:
np.linalg.matrix_rank(A42@A42)

0

In [65]:
P4 = np.asarray([[1,1],[1,0]])

In [75]:
P4i = np.linalg.inv(P4)
print(P4i)
J4 = np.asarray([[2,1],[0,2]])
print(J4)

[[ 0.  1.]
 [ 1. -1.]]
[[2 1]
 [0 2]]


In [76]:
P4@J4@P4i

array([[ 3., -1.],
       [ 1.,  1.]])

In [78]:
P4@np.asarray([[1, 100000],[0, 1]])@P4i

array([[ 100001., -100000.],
       [ 100000.,  -99999.]])

In [79]:
P4@np.asarray([[7, 100000],[0, 7]])@P4i

array([[ 100007., -100000.],
       [ 100000.,  -99993.]])

In [80]:
A5 = np.asarray([[-3, 2, -1], [0, -1, 1], [4, -4, 3]])

In [81]:
A5

array([[-3,  2, -1],
       [ 0, -1,  1],
       [ 4, -4,  3]])

In [83]:
np.poly(A5)

array([ 1.,  1., -1., -1.])

In [92]:
A51 = A5 - np.eye(3)
print(A51)
print(np.linalg.matrix_rank(A51))
print(np.linalg.matrix_rank(A51@A51))

[[-4.  2. -1.]
 [ 0. -2.  1.]
 [ 4. -4.  2.]]
2
2


In [93]:
A5m1 = A5 + np.eye(3)
print(A5m1)
print(np.linalg.matrix_rank(A5m1))
print(np.linalg.matrix_rank(A5m1@A5m1))

[[-2.  2. -1.]
 [ 0.  0.  1.]
 [ 4. -4.  4.]]
2
1


In [94]:
P5 = np.asarray([[0, 1, -1], [1, 1, 0], [2, 0, 1]])

In [97]:
P5i = np.linalg.inv(P5)
P5i

array([[ 1., -1.,  1.],
       [-1.,  2., -1.],
       [-2.,  2., -1.]])

In [99]:
J5 = np.asarray([[1, 0, 0], [0, -1, 1], [0, 0, -1]])

In [101]:
P5@J5@P5i

array([[-3.,  2., -1.],
       [ 0., -1.,  1.],
       [ 4., -4.,  3.]])

In [102]:
Aux5 = np.asarray([[1, 0, 0], [0, 100, 10000], [0, 0, 100]])

In [103]:
P5@Aux5@P5i

array([[-19900.,  20000., -10000.],
       [-20099.,  20199., -10099.],
       [  -198.,    198.,    -98.]])

In [105]:
AA = np.asarray([[0, 1], [0, 0]])
BB = AA.T
CC = np.asarray([[1, 0], [0, 0]])
print(AA@BB@CC)
print(AA@CC@BB)
print(BB@AA@CC)

[[1 0]
 [0 0]]
[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
