In [8]:
import math
import numpy as np
import cmath


In [9]:
# make sure complex op is what we want

In [5]:
z = complex(2, -1)
vz = np.asarray([z,z])

vz.dot(vz)

(6-8j)

In [10]:
vz@vz.conj()
# this is desired inner product 

(10+0j)

In [11]:
# Problem 1 

In [38]:
z1 = complex(2, -1)
z2 = complex(1, -1)
v1 = np.asarray([2,z1])
v2 = np.asarray([1,z2])

In [31]:
print(v1)
print(v1@v1.conj())
n1 = v1/np.sqrt(v1@v1.conj())
print(n1)

[2.+0.j 2.-1.j]
(9+0j)
[0.66666667+0.j         0.66666667-0.33333333j]


In [32]:
#v3 = v1@v2.conj()
scalar1 = v2@n1.conj()
print(scalar1)

(1.6666666666666665-0.3333333333333333j)


In [33]:
proj1 = scalar1*n1
print(proj1)

[1.11111111-0.22222222j 1.        -0.77777778j]


In [39]:
v2 = v2 - proj1
print(v2)

[-1.11111111e-01+0.22222222j  2.22044605e-16-0.22222222j]


In [40]:
n1@v2.conj() #~=0

(2.914335439641036e-16-1.8503717077085938e-17j)

In [41]:
v2@v2.conj() #1/9

(0.11111111111111112+0j)

In [42]:
n2 = v2/np.sqrt(v2@v2.conj())

In [44]:
n2 #ok 

array([-3.33333333e-01+0.66666667j,  6.66133815e-16-0.66666667j])

In [45]:
n2@n2.conj()

(0.9999999999999997+0j)

In [46]:
n1@n2.conj()

(8.881784197001252e-16+4.930380657631324e-32j)

In [47]:
### def inner
def inner(v1, v2):
    return v1@v2.conj()

In [48]:
inner(n1,n2)

(8.881784197001252e-16+4.930380657631324e-32j)

In [50]:
# Part 2 

In [52]:
A1 = np.asarray([[3, 2],
                [2, 0]])

In [54]:
np.poly(A1)

array([ 1., -3., -4.])

In [55]:
A2 = np.asarray(
[
    [10, complex(-2,-2)],
    [complex(-2,2), 8]
]
)

In [56]:
np.poly(A2)

array([  1.+0.00000000e+00j, -18.+1.23259516e-31j,  72.+1.25607397e-15j])

In [57]:
v21 = np.asarray([-1, complex(1,-1)])

In [58]:
inner(v21,v21)

(3+0j)

In [ ]:
v3 = v1@v2.conj()

In [60]:
A3 = np.asarray([[5, 5, 2],
                [5, 5, 2],
                [2, 2, 8]])

In [61]:
np.poly(A3)

array([ 1.00000000e+00, -1.80000000e+01,  7.20000000e+01,  3.19744231e-14])

In [62]:
P3 = np.asarray([[1, 1, 1],
                [-1, 1, 1],
                [0, -2, 1]])

In [65]:
(P3.T)@P3

array([[2, 0, 0],
       [0, 6, 0],
       [0, 0, 3]])