In [14]:
import numpy as np

In [13]:
##define T

In [19]:
T = np.asarray([
    [3, 0, -2],
    [0, -2, 3],
    [-2, 3, 0]
])
v = np.asarray([1,1,1])

In [10]:
T

array([[ 3,  0, -2],
       [ 0, -2,  3],
       [-2,  3,  0]])

In [15]:
T@(np.asarray([1,1,1]).T)

array([1, 1, 1])

In [16]:
T.dot(np.asarray([1,1,1]).T)

array([1, 1, 1])

In [58]:
def basis_of_T_invariant_subspace(T, v):
    vk = v
    cur = [v]
    prev = np.linalg.matrix_rank(np.asarray(cur))
    #print(prev)
    for i in range(min(T.shape[0], T.shape[1])):
        vkp = T@vk
        cur.append(vkp)
        if(np.linalg.matrix_rank(np.asarray(cur)) == prev):
            print(cur)
            cur = cur[:-1]
            return np.asarray(cur)
        vk = vkp
        prev = np.linalg.matrix_rank(np.asarray(cur))
       
                   

In [59]:
basis_of_T_invariant_subspace(T, np.asarray([1,1,1]))

[array([1, 1, 1]), array([1, 1, 1])]


array([[1, 1, 1]])

In [60]:
alpha2 = basis_of_T_invariant_subspace(T, np.asarray([3,2,-5]))
alpha2

[array([ 3,  2, -5]), array([ 19, -19,   0]), array([ 57,  38, -95])]


array([[  3,   2,  -5],
       [ 19, -19,   0]])

In [63]:
alpha3 = basis_of_T_invariant_subspace(T, np.asarray([1,0,0]))
alpha3

[array([1, 0, 0]), array([ 3,  0, -2]), array([13, -6, -6]), array([ 51,  -6, -44])]


array([[ 1,  0,  0],
       [ 3,  0, -2],
       [13, -6, -6]])

In [56]:
#np.linalg.solve(np.r_[alpha2, np.asarray([[0,0,0]])], np.asarray([57, 38, -57]))

In [74]:
np.linalg.solve(alpha3.T, np.asarray([ 51,  -6, -44]))

array([-19.,  19.,   1.])

In [75]:
alpha3.T@np.array([-19.,  19.,   1.])

array([ 51.,  -6., -44.])